### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by codeling** [panicsteve/w2wiki#10]
Big fan of your wiki, thanks for sharing!
Since I saw no license hint, I was wondering under which conditions you are releasing this code? I love what you've done and have started to adapt it to my use case already (see [codeling/w2wiki](https://github.com/codeling/w2wiki)); I'm feeling a bit queasy though because of the missing license information - would it be possible to add some hint regarding that? Thanks!

**Comment by panicsteve** [comment]
Thanks for pointing this out. I've added the MIT license to the project.

**Comment by codeling** [comment]
Thanks for the quick response and for adding the license!

I will keep posting my code adaptations in my fork - and would be glad about any feedback!
