### ISSUE TITLE
Re-add PHP 7.3 support?

### ISSUE THREAD

**Issue by za3k** [panicsteve/w2wiki#17]
You just updated the markdown libraries to add PHP 8 support. Unfortunately, this broke PHP 7.3 support. PHP 7.3 is the latest available in debian buster (one version ago, which I'm running), though 7.4 is available in the latest stable. The problems introduced were:
- `public string`, `protected int` etc are not available in 7.3. Many instances
- One => lambda function was added

`readme.txt` still says this supports PHP 4. Could you update the docs or fix the problem? Happy to provide a PR if you're okay patching the library as a solution, which is what I did.

**Comment by za3k** [comment]
Whoops, may have spoken too early. I'm actually seeing a number of issues with my install, even with these changes. Viewing every page shows the same thing, and every page edits to the same thing.

**Comment by panicsteve** [comment]
Thank you for the patch!
